name: Build and Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git config --global pull.rebase false 

          # git pull origin gh-pages --allow-unrelated-histories

      - name: Update Deludo repos
        run: |
            git pull --force --allow-unrelated-histories
            cd static/assets
            git pull --force --allow-unrelated-histories
            cd ../..

      - name: Commit build changes
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            mv ./build ..
            rm -rf *
            mv ../build .
            git checkout -b pages -f
            git add ./build -f
            cd build/assets
            git pull
            cd ../..
            git rm -f --cached build/assets
            rm -rf build/assets/.git
            git add -f build/assets
            git commit -m "build: Deploy build [ @$(date +%s) id:$(od -An -tx1 -N4 /dev/urandom | tr -d ' \n' | sed 's/../&/g')]"
            git push origin pages --force
            

