name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Git clone the repo MANUALLY
        run: git clone --recurse-submodules -j8 https://github.com/Deblok-Workshop/Deludo


      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Commit build changes
        run: |
          git checkout -b gh-pages
          git add ./build
          git commit -m "Deploying build to gh-pages"
          git push origin gh-pages
